import type { UnicodeBlock } from './unicodeCharacterMap';

export const unicodeBlocks: UnicodeBlock[] = [
  { label: 'Adlam', value: 'adlam', start: 0x1E900, end: 0x1E95F },
  { label: 'Aegean Numbers', value: 'aegean-numbers', start: 0x10100, end: 0x1013F },
  { label: 'Ahom', value: 'ahom', start: 0x11700, end: 0x1174F },
  { label: 'Alchemical Symbols', value: 'alchemical-symbols', start: 0x1F700, end: 0x1F77F },
  { label: 'Alphabetic Presentation Forms', value: 'alphabetic-presentation-forms', start: 0xFB00, end: 0xFB4F },
  { label: 'Anatolian Hieroglyphs', value: 'anatolian-hieroglyphs', start: 0x14400, end: 0x1467F },
  { label: 'Ancient Greek Musical Notation', value: 'ancient-greek-musical-notation', start: 0x1D200, end: 0x1D24F },
  { label: 'Ancient Greek Numbers', value: 'ancient-greek-numbers', start: 0x10140, end: 0x1018F },
  { label: 'Ancient Symbols', value: 'ancient-symbols', start: 0x10190, end: 0x101CF },
  { label: 'Arabic', value: 'arabic', start: 0x600, end: 0x6FF },
  { label: 'Arabic Extended A', value: 'arabic-extended-a', start: 0x8A0, end: 0x8FF },
  { label: 'Arabic Extended B', value: 'arabic-extended-b', start: 0x870, end: 0x89F },
  { label: 'Arabic Extended C', value: 'arabic-extended-c', start: 0x10EC0, end: 0x10EFF },
  { label: 'Arabic Mathematical Alphabetic Symbols', value: 'arabic-mathematical-alphabetic-symbols', start: 0x1EE00, end: 0x1EEFF },
  { label: 'Arabic Presentation Forms A', value: 'arabic-presentation-forms-a', start: 0xFB50, end: 0xFDFF },
  { label: 'Arabic Presentation Forms B', value: 'arabic-presentation-forms-b', start: 0xFE70, end: 0xFEFF },
  { label: 'Arabic Supplement', value: 'arabic-supplement', start: 0x750, end: 0x77F },
  { label: 'Armenian', value: 'armenian', start: 0x530, end: 0x58F },
  { label: 'Arrows', value: 'arrows', start: 0x2190, end: 0x21FF },
  { label: 'Avestan', value: 'avestan', start: 0x10B00, end: 0x10B3F },
  { label: 'Balinese', value: 'balinese', start: 0x1B00, end: 0x1B7F },
  { label: 'Bamum', value: 'bamum', start: 0xA6A0, end: 0xA6FF },
  { label: 'Bamum Supplement', value: 'bamum-supplement', start: 0x16800, end: 0x16A3F },
  { label: 'Basic Latin', value: 'basic-latin', start: 0x0, end: 0x7F },
  { label: 'Bassa Vah', value: 'bassa-vah', start: 0x16AD0, end: 0x16AFF },
  { label: 'Batak', value: 'batak', start: 0x1BC0, end: 0x1BFF },
  { label: 'Bengali', value: 'bengali', start: 0x980, end: 0x9FF },
  { label: 'Beria Erfe', value: 'beria-erfe', start: 0x16EA0, end: 0x16EDF },
  { label: 'Bhaiksuki', value: 'bhaiksuki', start: 0x11C00, end: 0x11C6F },
  { label: 'Block Elements', value: 'block-elements', start: 0x2580, end: 0x259F },
  { label: 'Bopomofo', value: 'bopomofo', start: 0x3100, end: 0x312F },
  { label: 'Bopomofo Extended', value: 'bopomofo-extended', start: 0x31A0, end: 0x31BF },
  { label: 'Box Drawing', value: 'box-drawing', start: 0x2500, end: 0x257F },
  { label: 'Brahmi', value: 'brahmi', start: 0x11000, end: 0x1107F },
  { label: 'Braille Patterns', value: 'braille-patterns', start: 0x2800, end: 0x28FF },
  { label: 'Buginese', value: 'buginese', start: 0x1A00, end: 0x1A1F },
  { label: 'Buhid', value: 'buhid', start: 0x1740, end: 0x175F },
  { label: 'Byzantine Musical Symbols', value: 'byzantine-musical-symbols', start: 0x1D000, end: 0x1D0FF },
  { label: 'Carian', value: 'carian', start: 0x102A0, end: 0x102DF },
  { label: 'Caucasian Albanian', value: 'caucasian-albanian', start: 0x10530, end: 0x1056F },
  { label: 'Chakma', value: 'chakma', start: 0x11100, end: 0x1114F },
  { label: 'Cham', value: 'cham', start: 0xAA00, end: 0xAA5F },
  { label: 'Cherokee', value: 'cherokee', start: 0x13A0, end: 0x13FF },
  { label: 'Cherokee Supplement', value: 'cherokee-supplement', start: 0xAB70, end: 0xABBF },
  { label: 'Chess Symbols', value: 'chess-symbols', start: 0x1FA00, end: 0x1FA6F },
  { label: 'Chorasmian', value: 'chorasmian', start: 0x10FB0, end: 0x10FDF },
  { label: 'CJK Compatibility', value: 'cjk-compatibility', start: 0x3300, end: 0x33FF },
  { label: 'CJK Compatibility Forms', value: 'cjk-compatibility-forms', start: 0xFE30, end: 0xFE4F },
  { label: 'CJK Compatibility Ideographs', value: 'cjk-compatibility-ideographs', start: 0xF900, end: 0xFAFF },
  { label: 'CJK Compatibility Ideographs Supplement', value: 'cjk-compatibility-ideographs-supplement', start: 0x2F800, end: 0x2FA1F },
  { label: 'CJK Radicals Supplement', value: 'cjk-radicals-supplement', start: 0x2E80, end: 0x2EFF },
  { label: 'CJK Strokes', value: 'cjk-strokes', start: 0x31C0, end: 0x31EF },
  { label: 'CJK Symbols And Punctuation', value: 'cjk-symbols-and-punctuation', start: 0x3000, end: 0x303F },
  { label: 'CJK Unified Ideographs', value: 'cjk-unified-ideographs', start: 0x4E00, end: 0x9FFF },
  { label: 'CJK Unified Ideographs Extension A', value: 'cjk-unified-ideographs-extension-a', start: 0x3400, end: 0x4DBF },
  { label: 'CJK Unified Ideographs Extension B', value: 'cjk-unified-ideographs-extension-b', start: 0x20000, end: 0x2A6DF },
  { label: 'CJK Unified Ideographs Extension C', value: 'cjk-unified-ideographs-extension-c', start: 0x2A700, end: 0x2B73F },
  { label: 'CJK Unified Ideographs Extension D', value: 'cjk-unified-ideographs-extension-d', start: 0x2B740, end: 0x2B81F },
  { label: 'CJK Unified Ideographs Extension E', value: 'cjk-unified-ideographs-extension-e', start: 0x2B820, end: 0x2CEAF },
  { label: 'CJK Unified Ideographs Extension F', value: 'cjk-unified-ideographs-extension-f', start: 0x2CEB0, end: 0x2EBEF },
  { label: 'CJK Unified Ideographs Extension G', value: 'cjk-unified-ideographs-extension-g', start: 0x30000, end: 0x3134F },
  { label: 'CJK Unified Ideographs Extension H', value: 'cjk-unified-ideographs-extension-h', start: 0x31350, end: 0x323AF },
  { label: 'CJK Unified Ideographs Extension I', value: 'cjk-unified-ideographs-extension-i', start: 0x2EBF0, end: 0x2EE5F },
  { label: 'CJK Unified Ideographs Extension J', value: 'cjk-unified-ideographs-extension-j', start: 0x323B0, end: 0x3347F },
  { label: 'Combining Diacritical Marks', value: 'combining-diacritical-marks', start: 0x300, end: 0x36F },
  { label: 'Combining Diacritical Marks Extended', value: 'combining-diacritical-marks-extended', start: 0x1AB0, end: 0x1AFF },
  { label: 'Combining Diacritical Marks For Symbols', value: 'combining-diacritical-marks-for-symbols', start: 0x20D0, end: 0x20FF },
  { label: 'Combining Diacritical Marks Supplement', value: 'combining-diacritical-marks-supplement', start: 0x1DC0, end: 0x1DFF },
  { label: 'Combining Half Marks', value: 'combining-half-marks', start: 0xFE20, end: 0xFE2F },
  { label: 'Common Indic Number Forms', value: 'common-indic-number-forms', start: 0xA830, end: 0xA83F },
  { label: 'Control Pictures', value: 'control-pictures', start: 0x2400, end: 0x243F },
  { label: 'Coptic', value: 'coptic', start: 0x2C80, end: 0x2CFF },
  { label: 'Coptic Epact Numbers', value: 'coptic-epact-numbers', start: 0x102E0, end: 0x102FF },
  { label: 'Counting Rod Numerals', value: 'counting-rod-numerals', start: 0x1D360, end: 0x1D37F },
  { label: 'Cuneiform', value: 'cuneiform', start: 0x12000, end: 0x123FF },
  { label: 'Cuneiform Numbers And Punctuation', value: 'cuneiform-numbers-and-punctuation', start: 0x12400, end: 0x1247F },
  { label: 'Currency Symbols', value: 'currency-symbols', start: 0x20A0, end: 0x20CF },
  { label: 'Cypriot Syllabary', value: 'cypriot-syllabary', start: 0x10800, end: 0x1083F },
  { label: 'Cypro Minoan', value: 'cypro-minoan', start: 0x12F90, end: 0x12FFF },
  { label: 'Cyrillic', value: 'cyrillic', start: 0x400, end: 0x4FF },
  { label: 'Cyrillic Extended A', value: 'cyrillic-extended-a', start: 0x2DE0, end: 0x2DFF },
  { label: 'Cyrillic Extended B', value: 'cyrillic-extended-b', start: 0xA640, end: 0xA69F },
  { label: 'Cyrillic Extended C', value: 'cyrillic-extended-c', start: 0x1C80, end: 0x1C8F },
  { label: 'Cyrillic Extended D', value: 'cyrillic-extended-d', start: 0x1E030, end: 0x1E08F },
  { label: 'Cyrillic Supplement', value: 'cyrillic-supplement', start: 0x500, end: 0x52F },
  { label: 'Deseret', value: 'deseret', start: 0x10400, end: 0x1044F },
  { label: 'Devanagari', value: 'devanagari', start: 0x900, end: 0x97F },
  { label: 'Devanagari Extended', value: 'devanagari-extended', start: 0xA8E0, end: 0xA8FF },
  { label: 'Devanagari Extended A', value: 'devanagari-extended-a', start: 0x11B00, end: 0x11B5F },
  { label: 'Dingbats', value: 'dingbats', start: 0x2700, end: 0x27BF },
  { label: 'Dives Akuru', value: 'dives-akuru', start: 0x11900, end: 0x1195F },
  { label: 'Dogra', value: 'dogra', start: 0x11800, end: 0x1184F },
  { label: 'Domino Tiles', value: 'domino-tiles', start: 0x1F030, end: 0x1F09F },
  { label: 'Duployan', value: 'duployan', start: 0x1BC00, end: 0x1BC9F },
  { label: 'Early Dynastic Cuneiform', value: 'early-dynastic-cuneiform', start: 0x12480, end: 0x1254F },
  { label: 'Egyptian Hieroglyph Format Controls', value: 'egyptian-hieroglyph-format-controls', start: 0x13430, end: 0x1345F },
  { label: 'Egyptian Hieroglyphs', value: 'egyptian-hieroglyphs', start: 0x13000, end: 0x1342F },
  { label: 'Egyptian Hieroglyphs Extended A', value: 'egyptian-hieroglyphs-extended-a', start: 0x13460, end: 0x143FF },
  { label: 'Elbasan', value: 'elbasan', start: 0x10500, end: 0x1052F },
  { label: 'Elymaic', value: 'elymaic', start: 0x10FE0, end: 0x10FFF },
  { label: 'Emoticons', value: 'emoticons', start: 0x1F600, end: 0x1F64F },
  { label: 'Enclosed Alphanumeric Supplement', value: 'enclosed-alphanumeric-supplement', start: 0x1F100, end: 0x1F1FF },
  { label: 'Enclosed Alphanumerics', value: 'enclosed-alphanumerics', start: 0x2460, end: 0x24FF },
  { label: 'Enclosed CJK Letters And Months', value: 'enclosed-cjk-letters-and-months', start: 0x3200, end: 0x32FF },
  { label: 'Enclosed Ideographic Supplement', value: 'enclosed-ideographic-supplement', start: 0x1F200, end: 0x1F2FF },
  { label: 'Ethiopic', value: 'ethiopic', start: 0x1200, end: 0x137F },
  { label: 'Ethiopic Extended', value: 'ethiopic-extended', start: 0x2D80, end: 0x2DDF },
  { label: 'Ethiopic Extended A', value: 'ethiopic-extended-a', start: 0xAB00, end: 0xAB2F },
  { label: 'Ethiopic Extended B', value: 'ethiopic-extended-b', start: 0x1E7E0, end: 0x1E7FF },
  { label: 'Ethiopic Supplement', value: 'ethiopic-supplement', start: 0x1380, end: 0x139F },
  { label: 'Garay', value: 'garay', start: 0x10D40, end: 0x10D8F },
  { label: 'General Punctuation', value: 'general-punctuation', start: 0x2000, end: 0x206F },
  { label: 'Geometric Shapes', value: 'geometric-shapes', start: 0x25A0, end: 0x25FF },
  { label: 'Geometric Shapes Extended', value: 'geometric-shapes-extended', start: 0x1F780, end: 0x1F7FF },
  { label: 'Georgian', value: 'georgian', start: 0x10A0, end: 0x10FF },
  { label: 'Georgian Extended', value: 'georgian-extended', start: 0x1C90, end: 0x1CBF },
  { label: 'Georgian Supplement', value: 'georgian-supplement', start: 0x2D00, end: 0x2D2F },
  { label: 'Glagolitic', value: 'glagolitic', start: 0x2C00, end: 0x2C5F },
  { label: 'Glagolitic Supplement', value: 'glagolitic-supplement', start: 0x1E000, end: 0x1E02F },
  { label: 'Gothic', value: 'gothic', start: 0x10330, end: 0x1034F },
  { label: 'Grantha', value: 'grantha', start: 0x11300, end: 0x1137F },
  { label: 'Greek And Coptic', value: 'greek-and-coptic', start: 0x370, end: 0x3FF },
  { label: 'Greek Extended', value: 'greek-extended', start: 0x1F00, end: 0x1FFF },
  { label: 'Gujarati', value: 'gujarati', start: 0xA80, end: 0xAFF },
  { label: 'Gunjala Gondi', value: 'gunjala-gondi', start: 0x11D60, end: 0x11DAF },
  { label: 'Gurmukhi', value: 'gurmukhi', start: 0xA00, end: 0xA7F },
  { label: 'Gurung Khema', value: 'gurung-khema', start: 0x16100, end: 0x1613F },
  { label: 'Halfwidth And Fullwidth Forms', value: 'halfwidth-and-fullwidth-forms', start: 0xFF00, end: 0xFFEF },
  { label: 'Hangul Compatibility Jamo', value: 'hangul-compatibility-jamo', start: 0x3130, end: 0x318F },
  { label: 'Hangul Jamo', value: 'hangul-jamo', start: 0x1100, end: 0x11FF },
  { label: 'Hangul Jamo Extended A', value: 'hangul-jamo-extended-a', start: 0xA960, end: 0xA97F },
  { label: 'Hangul Jamo Extended B', value: 'hangul-jamo-extended-b', start: 0xD7B0, end: 0xD7FF },
  { label: 'Hangul Syllables', value: 'hangul-syllables', start: 0xAC00, end: 0xD7AF },
  { label: 'Hanifi Rohingya', value: 'hanifi-rohingya', start: 0x10D00, end: 0x10D3F },
  { label: 'Hanunoo', value: 'hanunoo', start: 0x1720, end: 0x173F },
  { label: 'Hatran', value: 'hatran', start: 0x108E0, end: 0x108FF },
  { label: 'Hebrew', value: 'hebrew', start: 0x590, end: 0x5FF },
  { label: 'High Private Use Surrogates', value: 'high-private-use-surrogates', start: 0xDB80, end: 0xDBFF },
  { label: 'High Surrogates', value: 'high-surrogates', start: 0xD800, end: 0xDB7F },
  { label: 'Hiragana', value: 'hiragana', start: 0x3040, end: 0x309F },
  { label: 'Ideographic Description Characters', value: 'ideographic-description-characters', start: 0x2FF0, end: 0x2FFF },
  { label: 'Ideographic Symbols And Punctuation', value: 'ideographic-symbols-and-punctuation', start: 0x16FE0, end: 0x16FFF },
  { label: 'Imperial Aramaic', value: 'imperial-aramaic', start: 0x10840, end: 0x1085F },
  { label: 'Indic Siyaq Numbers', value: 'indic-siyaq-numbers', start: 0x1EC70, end: 0x1ECBF },
  { label: 'Inscriptional Pahlavi', value: 'inscriptional-pahlavi', start: 0x10B60, end: 0x10B7F },
  { label: 'Inscriptional Parthian', value: 'inscriptional-parthian', start: 0x10B40, end: 0x10B5F },
  { label: 'IPA Extensions', value: 'ipa-extensions', start: 0x250, end: 0x2AF },
  { label: 'Javanese', value: 'javanese', start: 0xA980, end: 0xA9DF },
  { label: 'Kaithi', value: 'kaithi', start: 0x11080, end: 0x110CF },
  { label: 'Kaktovik Numerals', value: 'kaktovik-numerals', start: 0x1D2C0, end: 0x1D2DF },
  { label: 'Kana Extended A', value: 'kana-extended-a', start: 0x1B100, end: 0x1B12F },
  { label: 'Kana Extended B', value: 'kana-extended-b', start: 0x1AFF0, end: 0x1AFFF },
  { label: 'Kana Supplement', value: 'kana-supplement', start: 0x1B000, end: 0x1B0FF },
  { label: 'Kanbun', value: 'kanbun', start: 0x3190, end: 0x319F },
  { label: 'Kangxi Radicals', value: 'kangxi-radicals', start: 0x2F00, end: 0x2FDF },
  { label: 'Kannada', value: 'kannada', start: 0xC80, end: 0xCFF },
  { label: 'Katakana', value: 'katakana', start: 0x30A0, end: 0x30FF },
  { label: 'Katakana Phonetic Extensions', value: 'katakana-phonetic-extensions', start: 0x31F0, end: 0x31FF },
  { label: 'Kawi', value: 'kawi', start: 0x11F00, end: 0x11F5F },
  { label: 'Kayah Li', value: 'kayah-li', start: 0xA900, end: 0xA92F },
  { label: 'Kharoshthi', value: 'kharoshthi', start: 0x10A00, end: 0x10A5F },
  { label: 'Khitan Small Script', value: 'khitan-small-script', start: 0x18B00, end: 0x18CFF },
  { label: 'Khmer', value: 'khmer', start: 0x1780, end: 0x17FF },
  { label: 'Khmer Symbols', value: 'khmer-symbols', start: 0x19E0, end: 0x19FF },
  { label: 'Khojki', value: 'khojki', start: 0x11200, end: 0x1124F },
  { label: 'Khudawadi', value: 'khudawadi', start: 0x112B0, end: 0x112FF },
  { label: 'Kirat Rai', value: 'kirat-rai', start: 0x16D40, end: 0x16D7F },
  { label: 'Lao', value: 'lao', start: 0xE80, end: 0xEFF },
  { label: 'Latin-1 Supplement', value: 'latin-1-supplement', start: 0x80, end: 0xFF },
  { label: 'Latin Extended A', value: 'latin-extended-a', start: 0x100, end: 0x17F },
  { label: 'Latin Extended Additional', value: 'latin-extended-additional', start: 0x1E00, end: 0x1EFF },
  { label: 'Latin Extended B', value: 'latin-extended-b', start: 0x180, end: 0x24F },
  { label: 'Latin Extended C', value: 'latin-extended-c', start: 0x2C60, end: 0x2C7F },
  { label: 'Latin Extended D', value: 'latin-extended-d', start: 0xA720, end: 0xA7FF },
  { label: 'Latin Extended E', value: 'latin-extended-e', start: 0xAB30, end: 0xAB6F },
  { label: 'Latin Extended F', value: 'latin-extended-f', start: 0x10780, end: 0x107BF },
  { label: 'Latin Extended G', value: 'latin-extended-g', start: 0x1DF00, end: 0x1DFFF },
  { label: 'Lepcha', value: 'lepcha', start: 0x1C00, end: 0x1C4F },
  { label: 'Letterlike Symbols', value: 'letterlike-symbols', start: 0x2100, end: 0x214F },
  { label: 'Limbu', value: 'limbu', start: 0x1900, end: 0x194F },
  { label: 'Linear A', value: 'linear-a', start: 0x10600, end: 0x1077F },
  { label: 'Linear B Ideograms', value: 'linear-b-ideograms', start: 0x10080, end: 0x100FF },
  { label: 'Linear B Syllabary', value: 'linear-b-syllabary', start: 0x10000, end: 0x1007F },
  { label: 'Lisu', value: 'lisu', start: 0xA4D0, end: 0xA4FF },
  { label: 'Lisu Supplement', value: 'lisu-supplement', start: 0x11FB0, end: 0x11FBF },
  { label: 'Low Surrogates', value: 'low-surrogates', start: 0xDC00, end: 0xDFFF },
  { label: 'Lycian', value: 'lycian', start: 0x10280, end: 0x1029F },
  { label: 'Lydian', value: 'lydian', start: 0x10920, end: 0x1093F },
  { label: 'Mahajani', value: 'mahajani', start: 0x11150, end: 0x1117F },
  { label: 'Mahjong Tiles', value: 'mahjong-tiles', start: 0x1F000, end: 0x1F02F },
  { label: 'Makasar', value: 'makasar', start: 0x11EE0, end: 0x11EFF },
  { label: 'Malayalam', value: 'malayalam', start: 0xD00, end: 0xD7F },
  { label: 'Mandaic', value: 'mandaic', start: 0x840, end: 0x85F },
  { label: 'Manichaean', value: 'manichaean', start: 0x10AC0, end: 0x10AFF },
  { label: 'Marchen', value: 'marchen', start: 0x11C70, end: 0x11CBF },
  { label: 'Masaram Gondi', value: 'masaram-gondi', start: 0x11D00, end: 0x11D5F },
  { label: 'Mathematical Alphanumeric Symbols', value: 'mathematical-alphanumeric-symbols', start: 0x1D400, end: 0x1D7FF },
  { label: 'Mathematical Operators', value: 'mathematical-operators', start: 0x2200, end: 0x22FF },
  { label: 'Mayan Numerals', value: 'mayan-numerals', start: 0x1D2E0, end: 0x1D2FF },
  { label: 'Medefaidrin', value: 'medefaidrin', start: 0x16E40, end: 0x16E9F },
  { label: 'Meetei Mayek', value: 'meetei-mayek', start: 0xABC0, end: 0xABFF },
  { label: 'Meetei Mayek Extensions', value: 'meetei-mayek-extensions', start: 0xAAE0, end: 0xAAFF },
  { label: 'Mende Kikakui', value: 'mende-kikakui', start: 0x1E800, end: 0x1E8DF },
  { label: 'Meroitic Cursive', value: 'meroitic-cursive', start: 0x109A0, end: 0x109FF },
  { label: 'Meroitic Hieroglyphs', value: 'meroitic-hieroglyphs', start: 0x10980, end: 0x1099F },
  { label: 'Miao', value: 'miao', start: 0x16F00, end: 0x16F9F },
  { label: 'Miscellaneous Mathematical Symbols A', value: 'miscellaneous-mathematical-symbols-a', start: 0x27C0, end: 0x27EF },
  { label: 'Miscellaneous Mathematical Symbols B', value: 'miscellaneous-mathematical-symbols-b', start: 0x2980, end: 0x29FF },
  { label: 'Miscellaneous Symbols', value: 'miscellaneous-symbols', start: 0x2600, end: 0x26FF },
  { label: 'Miscellaneous Symbols And Arrows', value: 'miscellaneous-symbols-and-arrows', start: 0x2B00, end: 0x2BFF },
  { label: 'Miscellaneous Symbols And Pictographs', value: 'miscellaneous-symbols-and-pictographs', start: 0x1F300, end: 0x1F5FF },
  { label: 'Miscellaneous Symbols Supplement', value: 'miscellaneous-symbols-supplement', start: 0x1CEC0, end: 0x1CEFF },
  { label: 'Miscellaneous Technical', value: 'miscellaneous-technical', start: 0x2300, end: 0x23FF },
  { label: 'Modi', value: 'modi', start: 0x11600, end: 0x1165F },
  { label: 'Modifier Tone Letters', value: 'modifier-tone-letters', start: 0xA700, end: 0xA71F },
  { label: 'Mongolian', value: 'mongolian', start: 0x1800, end: 0x18AF },
  { label: 'Mongolian Supplement', value: 'mongolian-supplement', start: 0x11660, end: 0x1167F },
  { label: 'Mro', value: 'mro', start: 0x16A40, end: 0x16A6F },
  { label: 'Multani', value: 'multani', start: 0x11280, end: 0x112AF },
  { label: 'Musical Symbols', value: 'musical-symbols', start: 0x1D100, end: 0x1D1FF },
  { label: 'Myanmar', value: 'myanmar', start: 0x1000, end: 0x109F },
  { label: 'Myanmar Extended A', value: 'myanmar-extended-a', start: 0xAA60, end: 0xAA7F },
  { label: 'Myanmar Extended B', value: 'myanmar-extended-b', start: 0xA9E0, end: 0xA9FF },
  { label: 'Myanmar Extended C', value: 'myanmar-extended-c', start: 0x116D0, end: 0x116FF },
  { label: 'Nabataean', value: 'nabataean', start: 0x10880, end: 0x108AF },
  { label: 'Nag Mundari', value: 'nag-mundari', start: 0x1E4D0, end: 0x1E4FF },
  { label: 'Nandinagari', value: 'nandinagari', start: 0x119A0, end: 0x119FF },
  { label: 'New Tai Lue', value: 'new-tai-lue', start: 0x1980, end: 0x19DF },
  { label: 'Newa', value: 'newa', start: 0x11400, end: 0x1147F },
  { label: 'NKo', value: 'nko', start: 0x7C0, end: 0x7FF },
  { label: 'Number Forms', value: 'number-forms', start: 0x2150, end: 0x218F },
  { label: 'Nushu', value: 'nushu', start: 0x1B170, end: 0x1B2FF },
  { label: 'Nyiakeng Puachue Hmong', value: 'nyiakeng-puachue-hmong', start: 0x1E100, end: 0x1E14F },
  { label: 'Ogham', value: 'ogham', start: 0x1680, end: 0x169F },
  { label: 'Ol Chiki', value: 'ol-chiki', start: 0x1C50, end: 0x1C7F },
  { label: 'Ol Onal', value: 'ol-onal', start: 0x1E5D0, end: 0x1E5FF },
  { label: 'Old Hungarian', value: 'old-hungarian', start: 0x10C80, end: 0x10CFF },
  { label: 'Old Italic', value: 'old-italic', start: 0x10300, end: 0x1032F },
  { label: 'Old North Arabian', value: 'old-north-arabian', start: 0x10A80, end: 0x10A9F },
  { label: 'Old Permic', value: 'old-permic', start: 0x10350, end: 0x1037F },
  { label: 'Old Persian', value: 'old-persian', start: 0x103A0, end: 0x103DF },
  { label: 'Old Sogdian', value: 'old-sogdian', start: 0x10F00, end: 0x10F2F },
  { label: 'Old South Arabian', value: 'old-south-arabian', start: 0x10A60, end: 0x10A7F },
  { label: 'Old Turkic', value: 'old-turkic', start: 0x10C00, end: 0x10C4F },
  { label: 'Old Uyghur', value: 'old-uyghur', start: 0x10F70, end: 0x10FAF },
  { label: 'Optical Character Recognition', value: 'optical-character-recognition', start: 0x2440, end: 0x245F },
  { label: 'Oriya', value: 'oriya', start: 0xB00, end: 0xB7F },
  { label: 'Ornamental Dingbats', value: 'ornamental-dingbats', start: 0x1F650, end: 0x1F67F },
  { label: 'Osage', value: 'osage', start: 0x104B0, end: 0x104FF },
  { label: 'Osmanya', value: 'osmanya', start: 0x10480, end: 0x104AF },
  { label: 'Ottoman Siyaq Numbers', value: 'ottoman-siyaq-numbers', start: 0x1ED00, end: 0x1ED4F },
  { label: 'Pahawh Hmong', value: 'pahawh-hmong', start: 0x16B00, end: 0x16B8F },
  { label: 'Palmyrene', value: 'palmyrene', start: 0x10860, end: 0x1087F },
  { label: 'Pau Cin Hau', value: 'pau-cin-hau', start: 0x11AC0, end: 0x11AFF },
  { label: 'Phags Pa', value: 'phags-pa', start: 0xA840, end: 0xA87F },
  { label: 'Phaistos Disc', value: 'phaistos-disc', start: 0x101D0, end: 0x101FF },
  { label: 'Phoenician', value: 'phoenician', start: 0x10900, end: 0x1091F },
  { label: 'Phonetic Extensions', value: 'phonetic-extensions', start: 0x1D00, end: 0x1D7F },
  { label: 'Phonetic Extensions Supplement', value: 'phonetic-extensions-supplement', start: 0x1D80, end: 0x1DBF },
  { label: 'Playing Cards', value: 'playing-cards', start: 0x1F0A0, end: 0x1F0FF },
  { label: 'Private Use Area', value: 'private-use-area', start: 0xE000, end: 0xF8FF },
  { label: 'Psalter Pahlavi', value: 'psalter-pahlavi', start: 0x10B80, end: 0x10BAF },
  { label: 'Rejang', value: 'rejang', start: 0xA930, end: 0xA95F },
  { label: 'Rumi Numeral Symbols', value: 'rumi-numeral-symbols', start: 0x10E60, end: 0x10E7F },
  { label: 'Runic', value: 'runic', start: 0x16A0, end: 0x16FF },
  { label: 'Samaritan', value: 'samaritan', start: 0x800, end: 0x83F },
  { label: 'Saurashtra', value: 'saurashtra', start: 0xA880, end: 0xA8DF },
  { label: 'Sharada', value: 'sharada', start: 0x11180, end: 0x111DF },
  { label: 'Sharada Supplement', value: 'sharada-supplement', start: 0x11B60, end: 0x11B7F },
  { label: 'Shavian', value: 'shavian', start: 0x10450, end: 0x1047F },
  { label: 'Shorthand Format Controls', value: 'shorthand-format-controls', start: 0x1BCA0, end: 0x1BCAF },
  { label: 'Siddham', value: 'siddham', start: 0x11580, end: 0x115FF },
  { label: 'Sidetic', value: 'sidetic', start: 0x10940, end: 0x1095F },
  { label: 'Sinhala', value: 'sinhala', start: 0xD80, end: 0xDFF },
  { label: 'Sinhala Archaic Numbers', value: 'sinhala-archaic-numbers', start: 0x111E0, end: 0x111FF },
  { label: 'Small Form Variants', value: 'small-form-variants', start: 0xFE50, end: 0xFE6F },
  { label: 'Small Kana Extension', value: 'small-kana-extension', start: 0x1B130, end: 0x1B16F },
  { label: 'Sogdian', value: 'sogdian', start: 0x10F30, end: 0x10F6F },
  { label: 'Sora Sompeng', value: 'sora-sompeng', start: 0x110D0, end: 0x110FF },
  { label: 'Soyombo', value: 'soyombo', start: 0x11A50, end: 0x11AAF },
  { label: 'Spacing Modifier Letters', value: 'spacing-modifier-letters', start: 0x2B0, end: 0x2FF },
  { label: 'Specials', value: 'specials', start: 0xFFF0, end: 0xFFFF },
  { label: 'Sundanese', value: 'sundanese', start: 0x1B80, end: 0x1BBF },
  { label: 'Sundanese Supplement', value: 'sundanese-supplement', start: 0x1CC0, end: 0x1CCF },
  { label: 'Sunuwar', value: 'sunuwar', start: 0x11BC0, end: 0x11BFF },
  { label: 'Superscripts And Subscripts', value: 'superscripts-and-subscripts', start: 0x2070, end: 0x209F },
  { label: 'Supplemental Arrows A', value: 'supplemental-arrows-a', start: 0x27F0, end: 0x27FF },
  { label: 'Supplemental Arrows B', value: 'supplemental-arrows-b', start: 0x2900, end: 0x297F },
  { label: 'Supplemental Arrows C', value: 'supplemental-arrows-c', start: 0x1F800, end: 0x1F8FF },
  { label: 'Supplemental Mathematical Operators', value: 'supplemental-mathematical-operators', start: 0x2A00, end: 0x2AFF },
  { label: 'Supplemental Punctuation', value: 'supplemental-punctuation', start: 0x2E00, end: 0x2E7F },
  { label: 'Supplemental Symbols And Pictographs', value: 'supplemental-symbols-and-pictographs', start: 0x1F900, end: 0x1F9FF },
  { label: 'Supplementary Private Use Area A', value: 'supplementary-private-use-area-a', start: 0xF0000, end: 0xFFFFF },
  { label: 'Supplementary Private Use Area B', value: 'supplementary-private-use-area-b', start: 0x100000, end: 0x10FFFF },
  { label: 'Sutton Signwriting', value: 'sutton-signwriting', start: 0x1D800, end: 0x1DAAF },
  { label: 'Syloti Nagri', value: 'syloti-nagri', start: 0xA800, end: 0xA82F },
  { label: 'Symbols And Pictographs Extended A', value: 'symbols-and-pictographs-extended-a', start: 0x1FA70, end: 0x1FAFF },
  { label: 'Symbols For Legacy Computing', value: 'symbols-for-legacy-computing', start: 0x1FB00, end: 0x1FBFF },
  { label: 'Symbols For Legacy Computing Supplement', value: 'symbols-for-legacy-computing-supplement', start: 0x1CC00, end: 0x1CEBF },
  { label: 'Syriac', value: 'syriac', start: 0x700, end: 0x74F },
  { label: 'Syriac Supplement', value: 'syriac-supplement', start: 0x860, end: 0x86F },
  { label: 'Tagalog', value: 'tagalog', start: 0x1700, end: 0x171F },
  { label: 'Tagbanwa', value: 'tagbanwa', start: 0x1760, end: 0x177F },
  { label: 'Tags', value: 'tags', start: 0xE0000, end: 0xE007F },
  { label: 'Tai Le', value: 'tai-le', start: 0x1950, end: 0x197F },
  { label: 'Tai Tham', value: 'tai-tham', start: 0x1A20, end: 0x1AAF },
  { label: 'Tai Viet', value: 'tai-viet', start: 0xAA80, end: 0xAADF },
  { label: 'Tai Xuan Jing Symbols', value: 'tai-xuan-jing-symbols', start: 0x1D300, end: 0x1D35F },
  { label: 'Tai Yo', value: 'tai-yo', start: 0x1E6C0, end: 0x1E6FF },
  { label: 'Takri', value: 'takri', start: 0x11680, end: 0x116CF },
  { label: 'Tamil', value: 'tamil', start: 0xB80, end: 0xBFF },
  { label: 'Tamil Supplement', value: 'tamil-supplement', start: 0x11FC0, end: 0x11FFF },
  { label: 'Tangsa', value: 'tangsa', start: 0x16A70, end: 0x16ACF },
  { label: 'Tangut', value: 'tangut', start: 0x17000, end: 0x187FF },
  { label: 'Tangut Components', value: 'tangut-components', start: 0x18800, end: 0x18AFF },
  { label: 'Tangut Components Supplement', value: 'tangut-components-supplement', start: 0x18D80, end: 0x18DFF },
  { label: 'Tangut Supplement', value: 'tangut-supplement', start: 0x18D00, end: 0x18D7F },
  { label: 'Telugu', value: 'telugu', start: 0xC00, end: 0xC7F },
  { label: 'Thaana', value: 'thaana', start: 0x780, end: 0x7BF },
  { label: 'Thai', value: 'thai', start: 0xE00, end: 0xE7F },
  { label: 'Tibetan', value: 'tibetan', start: 0xF00, end: 0xFFF },
  { label: 'Tifinagh', value: 'tifinagh', start: 0x2D30, end: 0x2D7F },
  { label: 'Tirhuta', value: 'tirhuta', start: 0x11480, end: 0x114DF },
  { label: 'Todhri', value: 'todhri', start: 0x105C0, end: 0x105FF },
  { label: 'Tolong Siki', value: 'tolong-siki', start: 0x11DB0, end: 0x11DEF },
  { label: 'Toto', value: 'toto', start: 0x1E290, end: 0x1E2BF },
  { label: 'Transport And Map Symbols', value: 'transport-and-map-symbols', start: 0x1F680, end: 0x1F6FF },
  { label: 'Tulu Tigalari', value: 'tulu-tigalari', start: 0x11380, end: 0x113FF },
  { label: 'Ugaritic', value: 'ugaritic', start: 0x10380, end: 0x1039F },
  { label: 'Unified Canadian Aboriginal Syllabics', value: 'unified-canadian-aboriginal-syllabics', start: 0x1400, end: 0x167F },
  { label: 'Unified Canadian Aboriginal Syllabics Extended', value: 'unified-canadian-aboriginal-syllabics-extended', start: 0x18B0, end: 0x18FF },
  { label: 'Unified Canadian Aboriginal Syllabics Extended A', value: 'unified-canadian-aboriginal-syllabics-extended-a', start: 0x11AB0, end: 0x11ABF },
  { label: 'Vai', value: 'vai', start: 0xA500, end: 0xA63F },
  { label: 'Variation Selectors', value: 'variation-selectors', start: 0xFE00, end: 0xFE0F },
  { label: 'Variation Selectors Supplement', value: 'variation-selectors-supplement', start: 0xE0100, end: 0xE01EF },
  { label: 'Vedic Extensions', value: 'vedic-extensions', start: 0x1CD0, end: 0x1CFF },
  { label: 'Vertical Forms', value: 'vertical-forms', start: 0xFE10, end: 0xFE1F },
  { label: 'Vithkuqi', value: 'vithkuqi', start: 0x10570, end: 0x105BF },
  { label: 'Wancho', value: 'wancho', start: 0x1E2C0, end: 0x1E2FF },
  { label: 'Warang Citi', value: 'warang-citi', start: 0x118A0, end: 0x118FF },
  { label: 'Yezidi', value: 'yezidi', start: 0x10E80, end: 0x10EBF },
  { label: 'Yi Radicals', value: 'yi-radicals', start: 0xA490, end: 0xA4CF },
  { label: 'Yi Syllables', value: 'yi-syllables', start: 0xA000, end: 0xA48F },
  { label: 'Yijing Hexagram Symbols', value: 'yijing-hexagram-symbols', start: 0x4DC0, end: 0x4DFF },
  { label: 'Zanabazar Square', value: 'zanabazar-square', start: 0x11A00, end: 0x11A4F },
  { label: 'Znamenny Musical Notation', value: 'znamenny-musical-notation', start: 0x1CF00, end: 0x1CFCF },
];
